[package]
name = "sqlx-example-postgres-axum-social"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Primary crates
axum = { version = "0.8.8", features = ["macros"] }
sqlx = { path = "../../../", features = [ "runtime-tokio", "tls-rustls-ring", "postgres", "time", "uuid" ] }
tokio = { version = "1.49.0", features = ["rt-multi-thread", "macros"] }

# Important secondary crates
argon2 = "0.5.3"
rand = "0.9.2"
regex = "1.12.2"
serde = "1.0.228"
serde_with = { version = "3.16.1", features = ["time_0_3"] }
time = "0.3.46"
uuid = { version = "1.20.0", features = ["serde"] }
validator = { version = "0.20.0", features = ["derive"] }

# Auxilliary crates
anyhow = "1.0.100"
dotenvy = "0.15.7"
thiserror = "2.0.18"
tracing = "0.1.44"

[dev-dependencies]
serde_json = "1.0.149"
tower = "0.5.3"
